# Generated by Django 5.1.3 on 2024-12-05 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_article_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_saham', models.CharField(max_length=10, unique=True)),
                ('nama_perusahaan', models.CharField(max_length=100)),
                ('jenis_saham', models.CharField(max_length=20)),
                ('saham', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='artikel_cover/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='judul',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.kategoriartikel'),
        ),
    ]
