# Generated by Django 5.1.3 on 2024-12-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_produk_alter_article_cover_alter_article_judul_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_saham', models.CharField(max_length=10, unique=True)),
                ('nama_perusahaan', models.CharField(max_length=100)),
                ('jenis_saham', models.CharField(max_length=20)),
                ('saham', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
