# Generated by Django 5.1.3 on 2024-12-15 00:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_datauser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_month', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Belum Dicek', 'Belum Dicek'), ('Ceklist', 'Ceklist')], default='Belum Dicek', max_length=15)),
                ('report_file', models.FileField(blank=True, help_text='Upload PDF laporan bulanan', null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
