# Generated by Django 5.1.3 on 2024-12-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_monthlyreport_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='imba_hasil',
            field=models.BigIntegerField(default=0, help_text='Input imba hasil dividen'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='total_imba_hasil',
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
