# Generated by Django 5.1.3 on 2024-12-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_monthlyreport_imba_hasil_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyreport',
            old_name='total_imba_hasil',
            new_name='total',
        ),
    ]
