# Generated by Django 5.1.3 on 2024-12-12 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_customuser_email_alter_customuser_role_and_more'),
        ('user', '0002_rdnwallet_rdntransaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SahamTransaction',
            new_name='RDNTransaction',
        ),
        migrations.AlterField(
            model_name='rdntransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='login.rdnwalletdetail'),
        ),
        migrations.DeleteModel(
            name='RDNWallet',
        ),
    ]
